---
title: "lab4c - iNaturalist"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load libraries
librarian::shelf(
  digest, dplyr, DT, purrr, readr, tidyr, keras, stringr)

```

# Lac 4c - iNaturalist
```{r}
# path to folder containing species directories of images
dir_train_mini <- "/courses/EDS232/inaturalist-2021/train_mini"

# path to output table of paths, which could be read by R, eg read_csv()
inat_spp_dirs_csv <- "~/inat_species_dirs.csv" # I don't see this csv in taylor??

# get list of directories, one per species (n = 10,000 species)
dirs_spp <- list.dirs(dir_train_mini, recursive = F)
n_spp <- length(dirs_spp)

# set seed (for reproducible results) 
# just before sampling (otherwise get different results)
# based on your username (unique amongst class)
Sys.info()[["user"]] %>% # sys.info pulls my user name
  digest::digest2int() %>% 
  set.seed()
i10 <- sample(1:n_spp, 10)

# show the 10 indices sampled of the 10,000 possible 
i10

# show the 10 species directory names
species_10 <- basename(dirs_spp)[i10]
species_10

# show the first 2 species directory names
i2 <- i10[1:2]
basename(dirs_spp)[i2]
```

```{r}
original_dataset_dir <- "/courses/EDS232/inaturalist-2021/train_mini"

# base
base_dir <- "/Users/jdecesaro/EDS232/eds232_lab4"

train_dir <- file.path(base_dir, "train")
validation_dir <- file.path(base_dir, "validation")
test_dir <- file.path(base_dir, "test")

# create folder for all 10 species
# for (i in 1:length(species_10)){
#   dir.create(file.path(train_dir, str_sub(species_10[[i]], start = 1, end = 5)), recursive = TRUE)
#   dir.create(file.path(validation_dir, str_sub(species_10[[i]], start = 1, end = 5)), recursive = TRUE)
#   dir.create(file.path(test_dir, str_sub(species_10[[i]], start = 1, end = 5)), recursive = TRUE)
# }
```

```{r}
# create test, validation, and training groups of images
# for(i in 1:length(species_10)){
#   # create 5 groups of 10 random samples
#   species_samples_10 <- replicate(5, 
#                                   sample(list.files(paste0(original_dataset_dir, "/", species_10[[i]]), 
#                                                     full.names = TRUE), replace = FALSE, 10))
#   ## train n = 30 ##
#   train <- rbind(species_samples_10[,1], species_samples_10[,2], species_samples_10[,3])
#   file.copy(from = train, 
#             to = paste0(train_dir, "/", str_sub(species_10[[i]], start = 1, end = 5)))
#   ## validation n = 10 ##
#   validate <- species_samples_10[,4]
#   file.copy(from = validate,
#             to = paste0(validation_dir, "/", str_sub(species_10[[i]], start = 1, end = 5)))
#   ## train n = 10 ##
#   test <- species_samples_10[,5]
#   file.copy(from = test,
#             to = paste0(test_dir, "/", str_sub(species_10[[i]], start = 1, end = 5)))
#   }
```

# Ben's code

```{r}
# path to output table of paths, which could be read by R, eg readr::read_csv(), or Python, eg pandas.read_csv()
inat_spp_images_csv <- "~/EDS232/eds232_lab4/inat_spp_images.csv"

d <- tibble(
  # get 10 species names
  species = basename(dirs_spp)[i10],
  # assign TRUE/FALSE for: 10 species (multi-class) and 2 species (binary)
  spp10 = TRUE,
  spp2  = c(T,T,rep(F,8)))
DT::datatable(d)
```

```{r}
d <- d %>% 
  mutate(
    # construct full path to species directory
    dir_species = file.path(dir_train_mini, species),
    tbl_images  = purrr::map(dir_species, function(dir){
      # create a tibble per species
      tibble(
        # list files in the species directory (n=50)
        image = list.files(dir),
        # assign subset per species
        subset = c(rep("train", 30), rep("validation", 10), rep("test", 10))) })) %>% 
  # go from a tibble with 10 species rows containing a nested tbl_images to unnested, ie 10 species * 50 images = 500 rows
  tidyr::unnest(tbl_images)

# write tibble to CSV file for subsequent reading
readr::write_csv(d, inat_spp_images_csv)

# show counts of image files per species and subset
d %>% 
  mutate(
    # truncate species to show one line per species
    species_trunc = stringr::str_trunc(species, 40)) %>% 
  select(species_trunc, subset) %>% 
  table()
```

# 2 Species (binary classification) - neural net.




```{r}
model <- keras_model_sequential() %>%
  layer_dense(units = 16, activation = "relu", input_shape = c(10000)) %>%
  layer_dense(units = 16, activation = "relu") %>%
  layer_dense(units = 1, activation = "sigmoid")

model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("accuracy"))
```

```{r}
summary(model)
```

```{r}
# All images will be rescaled by 1/255
train_datagen <- image_data_generator(rescale = 1/255)
validation_datagen <- image_data_generator(rescale = 1/255)
test_datagen <- image_data_generator(rescale = 1/255)

train_generator <- flow_images_from_directory(
  # This is the target directory
  train_dir,
  # This is the data generator
  train_datagen,
  # All images will be resized to 150x150
  target_size = c(150, 150),
  batch_size = 5,
  # Since we use binary_crossentropy loss, we need binary labels
  class_mode = "binary")

validation_generator <- flow_images_from_directory(
  validation_dir,
  validation_datagen,
  target_size = c(150, 150),
  batch_size = 5,
  class_mode = "binary")

test_generator <- flow_images_from_directory(
  test_dir,
  test_datagen,
  target_size = c(150, 150),
  batch_size = 5,
  class_mode = "binary")
```


```{r}
dir_models <- here::here("data/dl")
dir.create(dir_models, recursive=T, showWarnings = F)
mdl1_h5 <- file.path(dir_models, "INat_binary.h5")
mdl1_history_rds <- file.path(dir_models, "INat_binary_history.rds")
```

```{r}
# check if already fitted and saved model
if (!file.exists(mdl1_history_rds) | !file.exists(mdl1_h5)){
  # fit model
  history <- model %>% fit(
    train_generator,
    steps_per_epoch = 3,
    epochs = 10,
    validation_data = validation_generator,
    validation_steps = 5)
  # save fitted model and fitting history
  history %>% saveRDS(mdl1_history_rds)
  model %>% save_model_hdf5(mdl1_h5)
} else{
  # load previously fitted model
  history <- readRDS(mdl1_history_rds)
  model   <- load_model_hdf5(mdl1_h5)
}
```

# 2 Species (binary classification) - neural net.


